[package]
name = "compositor_render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pollster = "0.3.0"
thiserror = { workspace = true }
wgpu = "0.16.1"
compositor_common = { path = "../compositor_common" }
compositor_chromium = { path = "../compositor_chromium" }
image = { version = "0.24.6", features = ["jpeg", "png"] }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
bytes = { workspace = true }
log = { workspace = true }
bytemuck = { version = "1.13.1", features = ["derive"] }
glyphon = "0.3.0"
crossbeam-channel = { workspace = true }
resvg = "0.35.0"
nalgebra-glm = "0.18.0"

[dev-dependencies]
env_logger = { workspace = true }
