[package]
name = "video_compositor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "compositor_common",
    "compositor_render",
    "compositor_pipeline",
    "compositor_chromium",
]
resolver = "2"

[workspace.dependencies]
bytes = "1.4.0"
env_logger = "0.10.0"
serde_json = "1.0.99"
serde = { version = "1.0.164", features = ["derive", "rc"] }
log = "0.4.19"
thiserror = "1.0.40"
crossbeam-channel = "0.5.8"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }

[dependencies]
compositor_render = { path = "compositor_render" }
compositor_common = { path = "compositor_common" }
compositor_pipeline = { path = "compositor_pipeline" }
compositor_chromium = { path = "compositor_chromium" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = "1.0.71"
bytes = { workspace = true }
signal-hook = "0.3.15"
tiny_http = "0.12.0"
ffmpeg-next = "6.0.0"
crossbeam-channel = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true } 
usvg = "0.35.0"

[dev-dependencies]
reqwest = { workspace = true }
