[package]
name = "video_compositor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "compositor_common",
    "compositor_render",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0"

[dependencies]
compositor_render = { path = "compositor_render" }
