[package]
name = "video_compositor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "compositor_render",
]
resolver = "2"

[dependencies]
compositor_render = { path = "compositor_render" }
anyhow = "1.0.71"
bytes = "1.4.0"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"
signal-hook = "0.3.15"
tiny_http = "0.12.0"
thiserror = "1.0.41"
crossbeam = "0.8.2"
