[package]
name = "video_compositor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "compositor_common",
    "compositor_render",
    "compositor_pipeline",
]
resolver = "2"

[workspace.dependencies]
bytes = "1.4.0"
serde = { version = "1.0.164", features = ["derive"] }

[dependencies]
compositor_render = { path = "compositor_render" }
compositor_common = { path = "compositor_common" }
compositor_pipeline = { path = "compositor_pipeline" }
serde = { workspace = true }
anyhow = "1.0.71"
bytes =  { workspace = true }
serde_json = "1.0.99"
signal-hook = "0.3.15"
tiny_http = "0.12.0"
ffmpeg-next = "6.0.0"
crossbeam-channel = "0.5.8"
