[package]
name = "compositor_pipeline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
compositor_render = { path = "../compositor_render" }
bytes = { workspace = true }
crossbeam-channel = { workspace = true }
anyhow = "1.0.71"
thiserror = { workspace = true }
log = { workspace = true }
ffmpeg-next = { workspace = true }
rtp = { workspace = true }
webrtc-util = "0.8.0"
socket2 = "0.5.5"
rtcp = "0.10.0"
opus = "0.3.0"
rand = { workspace = true }
mp4 = "0.14.0"
reqwest = { workspace = true }
chrono = { workspace = true }
symphonia = { version = "0.5.3", default-features = false, features = ["isomp4", "aac"] }
fdk-aac-sys = "0.5.0"
