packages:
  - 'live-compositor'
  - '@live-compositor/core'
  - '@live-compositor/node'
  - '@live-compositor/browser-render'
  - 'examples/node-examples'
  - 'examples/vite-browser-render'
  - 'create-live-compositor'
  - 'create-live-compositor/templates/node-minimal'
  - 'create-live-compositor/templates/node-express-zustand'