[package]
name = "compositor_api"
version = "0.1.0"
edition = "2021"

[features]
decklink = ["compositor_pipeline/decklink"]
web_renderer = ["compositor_render/web_renderer"]

[dependencies]
compositor_pipeline = { path = "../compositor_pipeline" }
compositor_render = { path = "../compositor_render" }
serde = { workspace = true }
schemars = { workspace = true }
bytes = { workspace = true }
axum = { version = "0.7.4", features = ["ws"] }
