name: demos lint

on:
    workflow_dispatch: {}
    push:
        branches: [master]
        paths:
            - "demos/**"
    pull_request:
        types: [opened, synchronize]
        paths:
            - "demos/**"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  submodules: "true"

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with: 
                  version: 9
                  
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install project dependencies
              working-directory: ./demos
              run: pnpm install --frozen-lockfile

            - name: Lint code
              working-directory: ./demos
              run: pnpm run lint

            - name: Typecheck code
              working-directory: ./demos
              run: pnpm run typecheck
